name: Run Tests

on:

  pull_request:
    branches: [main]

job:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temvrin'
          java-version: 17
          cache: 'gradle'

      - name: Install Gradle
        run: chmod +x gradlew

      - name: run unit test
        run: ./gradlew clean testDebug

